### ISSUE TITLE
Specifying a additional inbound rule without any outbound rules will fail deployment

### ISSUE THREAD

**Issue by aukevanleeuwen** [linode/cloud-firewall-controller#16]
Specifying 

```yaml
firewall:
  inbound:
  - action: ACCEPT
    addresses:
      ipv4:
      - 192.168.128.0/17
    description: Node exporter is exposed (by design) on the host network. Prometheus
      needs access to scrape.
    label: ALLOW-prometheus-to-scrape-node-exporter
    ports: "9100"
    protocol: TCP
```

in the `values.yaml` file without any `outbound` rules, results in the following error while deploying:

```
helm_release.linode_firewall_controller: Creating...
╷
│ Error: template: cloud-firewall-controller/templates/firewall.yaml:10:15: executing "cloud-firewall-controller/templates/firewall.yaml" at <len .Values.firewall.outbound>: error calling len: len of nil pointer
│ 
│   with helm_release.linode_firewall_controller,
│   on main.tf line 70, in resource "helm_release" "linode_firewall_controller":
│   70: resource "helm_release" "linode_firewall_controller" {
│ 
╵
```

Obviously, it's easily fixed by adding a `[]` as `outbound` rules as well.
